### ISSUE TITLE
PHP 8.0.0 error due to incompatable dependency version

### ISSUE THREAD

**Issue by shaunfreeman** [mezzio/mezzio-problem-details#10]
On PHP 8.0.0 an error is thrown. this is due to match becoming a reserved name this has been fixed bu the dependency author willdurand/negotiation. this composer JSON needs to reflect this to bump the version to ^3.0

|    Q        |   A
|------------ | ------
| Version(s)  1.2.0

#### Summary
In PHP 8.0.0 throws an unexpected error message

#### Current behavior
An unexpected error occurred; stack trace:

ParseError raised in file /home/cms/vendor/willdurand/negotiation/src/Negotiation/Negotiator.php line 41:
Message: syntax error, unexpected token "match"
Stack Trace:
```
#0 /home/cms/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/cms/vendo...')
#1 /home/cms/vendor/mezzio/mezzio-problem-details/src/ProblemDetailsMiddleware.php(102):
Composer\Autoload\ClassLoader->loadClass('Negotiation\\Neg...')
#2 /home/cms/vendor/mezzio/mezzio-problem-details/src/ProblemDetailsMiddleware.php(54):
Mezzio\ProblemDetails\ProblemDetailsMiddleware->canActAsErrorHandler(Object(Laminas\Diactoros\ServerRequest))
#3 /home/cms/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47):
Mezzio\ProblemDetails\ProblemDetailsMiddleware->process(Object(Laminas\Diactoros\ServerRequest),
Object(Laminas\Stratigility\Next))
#4 /home/cms/vendor/laminas/laminas-stratigility/src/Next.php(61):
Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest),
Object(Laminas\Stratigility\Next))
#5 /home/cms/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(144):
Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#6 /home/cms/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47):
Laminas\Stratigility\Middleware\ErrorHandler->process(Object(Laminas\Diactoros\ServerRequest),
Object(Laminas\Stratigility\Next))
#7 /home/cms/vendor/laminas/laminas-stratigility/src/Next.php(61):
Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest),
Object(Laminas\Stratigility\Next))
#8 /home/cms/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84):
Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#9 /home/cms/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73):
Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest),
Object(Laminas\Stratigility\EmptyPipelineHandler))
#10 /home/cms/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96):
Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#11 /home/cms/vendor/mezzio/mezzio/src/Application.php(82): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#12 /home/cms/public/index.php(28): Mezzio\Application->run()
#13 /home/cms/public/index.php(29): {closure}()
#14 {main}
```
#### How to reproduce

run on PHP 8.0.0

#### Expected behavior
no error message

**Comment by agustingomes** [comment]
This is not a direct issue in this library. I created the appropriate issue in the right library: https://github.com/willdurand/Negotiation/issues/110

**Comment by froschdesign** [comment]
@agustingomes 
Have you checked the latest version of Negotiation? See: https://github.com/willdurand/Negotiation/releases/tag/3.0.0

**Comment by agustingomes** [comment]
@froschdesign ah nice, I missed that. then I'll go ahead and close that ticket in the negotiation package.

**Comment by weierophinney** [comment]
Does this mean we need to add support for willdurand/negotiation 3.0 to this package?

**Comment by shaunfreeman** [comment]
After manually installing  willdurand/negotiation 3.0 the problem went away. So yes support for version 3.0 is required for this package.

**Comment by boesing** [comment]
> Does this mean we need to add support for willdurand/negotiation 3.0 to this package?

And we have to add PHP 8.0 support at all as this package does not even support the constraint.
There is a reason why `--ignore-platform-reqs` should not be used for production.

This package is not PHP 8 ready, yet. But I'll add the `willdurand/negotiation` v3 information to the issue checklist.
