### ISSUE TITLE
`ProblemDetailsExceptionInterface` should extend `Throwable`

### ISSUE THREAD

**Issue by boesing** [mezzio/mezzio-problem-details#4]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | yes

#### Summary

The `ProblemDetailsExceptionInterface` does not extend `Throwable` and thus, it cannot be used as a return type for `throws`. 

This doesn't matter unless you are using static code analysers.

I want to propose extending the `Throwable` interface for the `ProblemDetailsExceptionInterface` as in most cases, this might be the use case anyway.

**Comment by Ocramius** [comment]
Overall, `ProblemDetailsExceptionInterface` is designed as marker for `Throwable` types anyway, so adding this is not really a BC Break.

**Comment by boesing** [comment]
Can you explain this more? 
I dont get it as technically it would be a bc break. Just trying to understand this.
You mean, because the `ProblemDetailsResponseFactory` is checking for the Interface within the `fromThrowable` method?

**Comment by Ocramius** [comment]
> I dont get it as technically it would be a bc break.

If the interface is used on something different from an `Exception` implementation, then yes, but in practice, that scenario can be excluded (and it is 100% misuse of this interface).

 > You mean, because the `ProblemDetailsResponseFactory` is checking for the Interface within the `fromThrowable` method?

You labeled this issues as a `BC Break`, but it isn't (in my opinion).
The BC break is only for third-party consumers that decided to implement `ProblemDetailsExceptionInterface` on their own, and don't do so on non-`Throwable` implementations.

**Comment by weierophinney** [comment]
@boesing A "marker interface" is one that defines no behavior and only exists to differentiate types. In this case, what @Ocramius is saying is since the interface exists only to decorate/differentiate `Throwable` types, having it extend that type is not a BC break.

**Comment by weierophinney** [comment]
(Sorry for adding my comment - screen hadn't refreshed to show the one from @Ocramius (grrrrrr)).
