### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by acelaya** [mezzio/mezzio-problem-details#45]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | yes

#### Summary

I've seen many other mezzio and laminas components have been updated to support PHP 8.3

 I can add support for this one if needed.

**Comment by froschdesign** [comment]
@acelaya 
Any help is welcome! Create a pull request.
Thanks in advance! 👍🏻
